import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	ignoreRegExpList: [
		'  version ".+', // Ignore version strings in Ruby files
	],
	words: [
		'archagon',
		'binarycookies',
		'bohemiancoding',
		'brettterpstra',
		'cadova',
		'charliemonroe',
		'crashreporter',
		'eney',
		'flashprint',
		'Flashprint',
		'Kenndac',
		'livecheck',
		'machatoapp',
		'mailarchiverx',
		'mothsoftware',
		'Msedit',
		'nkallen',
		'oakctl',
		'peterborgapps',
		'plausiblelabs',
		'postflight',
		'publicspace',
		'rlkey',
		'screenstudio',
		'screenstudioassets',
		'sensiblesidebuttons',
		'sharedfilelist',
		'sheepshaver',
		'sonoma',
		'timpler',
		'wpdos',
	],
})
